# Visit the docs for a full walktrough of this file
# https://vippstech.no/docs/default/component/vce-backstage

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vipps-login-hyva-magento
  description: this is vipps-login-hyva-magento
  annotations:
    # backstage.io/techdocs-ref: dir:. # create and place all documentation .MD files under /docs. Uncomment to enable docs
    backstage.io/kubernetes-label-selector: 'app=vipps-login-hyva-magento' # the same name as in kubernetes
    github.com/project-slug: 'vippsas/vipps-login-hyva-magento' # to enable CI/CD from GitHub
    # azure.com/tag-selector: app/vipps-login-hyva-magento # tag key and value to pull your Azure resources in relation to this entity
spec:
  type: service
  lifecycle: experimental
  owner: plugin-owners
